export const ADMIN_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAIL = "USER_LOGIN_FAIL"


export const ADD_BIKES_REQUEST = "ADD_BIKES_REQUEST"
export const ADD_BIKES_SUCCESS = "ADD_BIKES_SUCCESS"
export const ADD_BIKES_FAIL = "ADD_BIKES_FAIL"


export const ADMIN_LOGOUT = "ADMIN_LOGOUT"

export const BIKE_EDIT_REQUEST = "BIKE_EDIT_REQUEST"
export const BIKE_EDIT_SUCCESS = "BIKE_EDIT_SUCCESS"
export const BIKE_EDIT_FAIL = "BIKE_EDIT_FAIL"


export const BIKE_DELETE_REQUEST = "BIKE_DELETE_REQUEST"
export const BIKE_DELETE_SUCCESS = "BIKE_DELETE_SUCCESS"
export const BIKE_DELETE_FAIL = "BIKE_DELETE_FAIL"


export const ADMIN_USER_REQUEST = "ADMIN_USER_REQUEST"
export const ADMIN_USER_SUCCESS = "ADMIN_USER_SUCCESS"
export const ADMIN_USER_FAIL = "ADMIN_USER_FAIL"

export const ADMIN_RENTAL_REQUEST = "ADMIN_RENTAL_REQUEST"
export const ADMIN_RENTAL_SUCCESS = "ADMIN_RENTAL_SUCCESS"
export const ADMIN_RENTAL_FAIL = "ADMIN_RENTAL_FAIL"