export const GET_BIKE_REQUEST = "GET_BIKE_REQUEST"
export const GET_BIKE_SUCCESS = "GET_BIKE_SUCCESS"
export const GET_BIKE_FAIL = "GET_BIKE_FAIL"


export const BIKE_DETAIL_REQUEST = "BIKE_DETAIL_REQUEST"
export const BIKE_DETAIL_SUCCESS = "BIKE_DETAIL_SUCCESS"
export const BIKE_DETAIL_FAIL = "BIKE_DETAIL_FAIL"