export const ADD_RENTAL_REQUEST = "ADD_RENTAL_REQUEST"
export const ADD_RENTAL_SUCCESS = "ADD_RENTAL_SUCCESS"
export const ADD_RENTAL_FAIL = "ADD_RENTAL_FAIL"


export const GET_RENTAL_REQUEST = "GET_RENTAL_REQUEST"
export const GET_RENTAL_SUCCESS ="GET_RENTAL_SUCCESS"
export const GET_RENTAL_FAIL = "GET_RENTAL_FAIL"

export const DELETE_RENTAL_REQUEST = "DELETE_RENTAL_REQUEST"
export const DELETE_RENTAL_SUCCESS = "DELETE_RENTAL_SUCCESS"
export const DELETE_RENTAL_FAIL = "DELETE_RENTAL_FAIL"